version: '3'

services:
  erlang:
    image: erlang:22.3.4.13
    volumes:
      - ../:/emqx_auth_pgsql
    networks:
      - emqx_bridge
    depends_on:
      - pgsql_server
    tty: true

  pgsql_server:
    build:
        context: ./pgsql
        args:
            BUILD_FROM: postgres:${PGSQL_TAG}
    image: emqx-pgsql
    restart: always
    environment:
      POSTGRES_PASSWORD: public
      POSTGRES_USER: root
      POSTGRES_DB: mqtt
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
