##--------------------------------------------------------------------
## Broker
##--------------------------------------------------------------------
broker:
  ## System interval of publishing $SYS messages.
  ##
  ## Value: Duration
  ## Default: 1m, 1 minute
  sys_msg_interval: 1m

  ## System heartbeat interval of publishing following heart beat message:
  ##  - "$SYS/brokers/<node>/uptime"
  ##  - "$SYS/brokers/<node>/datetime"
  ##
  ## Value: Duration
  ## Default: 30s
  sys_heartbeat_interval: 30s

  ## Session locking strategy in a cluster.
  ##
  ## Value: Enum
  ## - local
  ## - one
  ## - quorum
  ## - all
  session_locking_strategy: quorum

  ## Dispatch strategy for shared subscription
  ##
  ## Value: Enum
  ## - random
  ## - round_robin
  ## - sticky
  ## - hash
  shared_subscription_strategy: random

  ## Enable/disable shared dispatch acknowledgement for QoS1 and QoS2 messages
  ## This should allow messages to be dispatched to a different subscriber in
  ## the group in case the picked (based on shared_subscription_strategy) one # is offline
  ##
  ## Value: Enum
  ## - true
  ## - false
  shared_dispatch_ack_enabled: false

  ## Enable batch clean for deleted routes.
  ##
  ## Value: Flag
  route_batch_clean: off